# Simple workflow for deploying static content to GitHub Pages
name: Deploy documentation

on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: 'Reference to build the docs from'
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
          cache-dependency-path: docs/yarn.lock
      - name: Build docs
        working-directory: docs
        run: |
          yarn install --frozen-lockfile
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'docs/.vitepress/dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
